// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        "DefaultFirebaseOptions have not been configured for web - "
        "you can reconfigure this by running the FlutterFire CLI again.",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for fuchsia - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      /*default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );*/
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCLX2bCNPxwlFmMD70rhIFfRq-GRaFikx0",
    appId: "1:11630227735:android:bd9afb69749b92ddbf8752",
    messagingSenderId: "11630227735",
    projectId: "realtime-database-demo-ed1c0",
    storageBucket: "realtime-database-demo-ed1c0.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAypCqFyND8wey8TkGv1XG_0n5N5OR4GwI",
    appId: "1:11630227735:ios:9edf814607b52c59bf8752",
    messagingSenderId: "11630227735",
    projectId: "realtime-database-demo-ed1c0",
    storageBucket: "realtime-database-demo-ed1c0.appspot.com",
    androidClientId:
        "11630227735-ljibne4dpja66ndnndbvsmr2mi2jddol.apps.googleusercontent.com",
    iosClientId:
        "11630227735-ebkgm2m1shjtajbd5glvraanabtbuj35.apps.googleusercontent.com",
    iosBundleId: "com.app.notificationapps",
  );
}
